CREATE DATABASE IF NOT EXISTS todoDb_test;

CREATE USER IF NOT EXISTS 'todoUser'@'%' IDENTIFIED BY 'todoPwd';

GRANT ALL PRIVILEGES ON todoDb_test.* TO 'todoUser'@'%';
FLUSH PRIVILEGES;

USE todoDb_test;

CREATE TABLE IF NOT EXISTS todo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL
);
